USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_INSTITUICAO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_INSTITUICAO INT,
			@NOME VARCHAR(45),
			@NOME_AUX VARCHAR(45)

	DECLARE C_DIM_INSTITUICAO CURSOR FOR 			
	SELECT COD_INSTITUICAO,NOME 
	FROM TB_AUX_INSTITUICAO
	WHERE DATA_CARGA = @DATA_CARGA


	OPEN C_DIM_INSTITUICAO
	FETCH C_DIM_INSTITUICAO INTO @COD_INSTITUICAO, @NOME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF NOT EXISTS (SELECT 1 FROM DIM_INSTITUICAO WHERE COD_INSTITUICAO = @COD_INSTITUICAO)
		BEGIN

			INSERT INTO DIM_INSTITUICAO
			VALUES (@COD_INSTITUICAO,@NOME)
			
		END
		ELSE
		BEGIN
			SELECT @NOME_AUX = I.NOME
			FROM DIM_INSTITUICAO I
			WHERE I.COD_INSTITUICAO = @COD_INSTITUICAO

			IF @NOME_AUX <> @NOME
			BEGIN
				UPDATE DIM_INSTITUICAO
				SET NOME = @NOME
				WHERE COD_INSTITUICAO = @COD_INSTITUICAO
			END
		END
		FETCH C_DIM_INSTITUICAO INTO @COD_INSTITUICAO, @NOME
		END
	CLOSE C_DIM_INSTITUICAO
	DEALLOCATE C_DIM_INSTITUICAO
END



-- Teste

EXEC SP_DIM_INSTITUICAO'20240120'
