USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_SECRETARIA(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_SECRETARIA INT,
			@NOME VARCHAR(45),
			@NOME_AUX VARCHAR(45)

	DECLARE C_DIM_SECRETARIA CURSOR FOR 			
	SELECT COD_SECRETARIA,NOME 
	FROM TB_AUX_SECRETARIA
	WHERE DATA_CARGA = @DATA_CARGA


	OPEN C_DIM_SECRETARIA
	FETCH C_DIM_SECRETARIA INTO @COD_SECRETARIA, @NOME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF NOT EXISTS (SELECT 1 FROM DIM_SECRETARIA WHERE COD_SECRETARIA = @COD_SECRETARIA)
		BEGIN

			INSERT INTO DIM_SECRETARIA
			VALUES (@COD_SECRETARIA,@NOME)
			
		END
		ELSE
		BEGIN
			SELECT @NOME_AUX = S.NOME
			FROM DIM_SECRETARIA S
			WHERE S.COD_SECRETARIA = @COD_SECRETARIA

			IF @NOME_AUX <> @NOME
			BEGIN
				UPDATE DIM_SECRETARIA
				SET NOME = @NOME
				WHERE COD_SECRETARIA = @COD_SECRETARIA
			END
		END
		FETCH C_DIM_SECRETARIA INTO @COD_SECRETARIA, @NOME
		END
	CLOSE C_DIM_SECRETARIA
	DEALLOCATE C_DIM_SECRETARIA
END



-- Teste

EXEC SP_DIM_SECRETARIA'20240120'

SELECT * FROM DIM_SECRETARIA