USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_TIPO_VEICULO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_TIPO_VEICULO INT,
			@NOME VARCHAR(45),
			@CURRENT_TIPO_VEICULO VARCHAR(45)

	DECLARE CURSO CURSOR FOR 			
	SELECT COD_TIPO_VEICULO,NOME FROM TB_AUX_TIPO_VEICULO

	OPEN CURSO
	FETCH CURSO INTO @COD_TIPO_VEICULO, @NOME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS(SELECT 1 FROM DIM_TIPO_VEICULO WHERE COD_TIPO_VEICULO = @COD_TIPO_VEICULO))
		BEGIN
			SELECT @CURRENT_TIPO_VEICULO = NOME
			FROM DIM_TIPO_VEICULO
			WHERE COD_TIPO_VEICULO = @COD_TIPO_VEICULO

			IF(@CURRENT_TIPO_VEICULO != @NOME)
				UPDATE DIM_TIPO_VEICULO
				SET NOME = @NOME
		END
		ELSE
		BEGIN
			INSERT INTO DIM_TIPO_VEICULO
			VALUES (@COD_TIPO_VEICULO,@NOME)
		END
		FETCH CURSO INTO @COD_TIPO_VEICULO, @NOME
	END
	CLOSE CURSO
	DEALLOCATE CURSO
END



-- Teste

EXEC SP_DIM_TIPO_VEICULO '20240120'

SELECT * FROM DIM_TIPO_VEICULO