USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_TIPO_VEICULO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_TIPO_VEICULO INT,
			@NOME VARCHAR(45),
			@NOME_AUX VARCHAR(45)

	DECLARE C_DIM_TIPO_VEICULO CURSOR FOR 			
	SELECT COD_TIPO_VEICULO,NOME 
	FROM TB_AUX_TIPO_VEICULO
	WHERE DATA_CARGA = @DATA_CARGA

	OPEN C_DIM_TIPO_VEICULO
	FETCH C_DIM_TIPO_VEICULO INTO @COD_TIPO_VEICULO, @NOME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF NOT EXISTS (SELECT 1 FROM DIM_TIPO_VEICULO WHERE COD_TIPO_VEICULO = @COD_TIPO_VEICULO)
		BEGIN

			INSERT INTO DIM_TIPO_VEICULO
			VALUES (@COD_TIPO_VEICULO,@NOME)
			
		END
		ELSE
		BEGIN
			SELECT @NOME_AUX = T.NOME
			FROM DIM_TIPO_VEICULO T
			WHERE T.COD_TIPO_VEICULO = @COD_TIPO_VEICULO

			IF @NOME_AUX <> @NOME
			BEGIN
				UPDATE DIM_TIPO_VEICULO
				SET NOME = @NOME
				WHERE COD_TIPO_VEICULO = @COD_TIPO_VEICULO
			END
		END
		FETCH C_DIM_TIPO_VEICULO INTO @COD_TIPO_VEICULO, @NOME
		END
	CLOSE C_DIM_TIPO_VEICULO
	DEALLOCATE C_DIM_TIPO_VEICULO
END



-- Teste

EXEC SP_DIM_TIPO_VEICULO '20240120'

SELECT * FROM DIM_TIPO_VEICULO