USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_MODALIDADE(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_MODALIDADE INT,
			@TIPO VARCHAR(10),
			@CURRENT_MODALIDADE VARCHAR(45)

	DECLARE CURSO CURSOR FOR 			
	SELECT COD_MODALIDADE,TIPO FROM TB_AUX_MODALIDADE

	OPEN CURSO
	FETCH CURSO INTO @COD_MODALIDADE, @TIPO

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS(SELECT 1 FROM DIM_MODALIDADE WHERE COD_MODALIDADE = @COD_MODALIDADE))
		BEGIN
			SELECT @CURRENT_MODALIDADE = TIPO
			FROM DIM_MODALIDADE
			WHERE COD_MODALIDADE = @COD_MODALIDADE

			IF(@CURRENT_MODALIDADE != @TIPO)
				UPDATE DIM_MODALIDADE
				SET TIPO = @TIPO
		END
		ELSE
		BEGIN
			INSERT INTO DIM_MODALIDADE
			VALUES (@COD_MODALIDADE,@TIPO)
		END
		FETCH CURSO INTO @COD_MODALIDADE, @TIPO
	END
	CLOSE CURSO
	DEALLOCATE CURSO
END



-- Teste

EXEC SP_DIM_MODALIDADE'20230323'

SELECT * FROM DIM_MODALIDADE
