USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_FATO_CONTRATO_INSTITUICAO_MENSAL
AS
BEGIN
		DECLARE @ID_TEMPO BIGINT,
				@MES INT,
				@ANO INT,
				@ID_LOJA INT,
				@VALOR NUMERIC(10,2)

		DELETE FROM FATO_CONTRATO_INSTITUICAO_MENSAL

		DECLARE C_CONTRATO_INSTITUICAO_MENSAL CURSOR FOR
		SELECT ID_TEMPO, MES, ANO
		FROM DIM_TEMPO
		WHERE NIVEL = 'MES'

		OPEN C_CONTRATO_INSTITUICAO_MENSAL
		FETCH NEXT FROM C_CONTRATO_INSTITUICAO_MENSAL INTO @ID_TEMPO,@MES, @ANO

		WHILE @@FETCH_STATUS = 0
		BEGIN
				INSERT INTO FATO_CONTRATO_INSTITUICAO_MENSAL
				SELECT @ID_TEMPO,C.ID_INSTITUICAO, SUM(C.VALOR), SUM(C.QUANTIDADE)
				FROM FATO_CONTRATO C
				INNER JOIN DIM_TEMPO T ON C.ID_TEMPO = T.ID_TEMPO
				WHERE MONTH(T.DATA) = @MES AND YEAR(T.DATA) = @ANO
				GROUP BY C.ID_INSTITUICAO

			FETCH NEXT FROM C_CONTRATO_INSTITUICAO_MENSAL INTO @ID_TEMPO,@MES, @ANO
		END
	CLOSE C_CONTRATO_INSTITUICAO_MENSAL
	DEALLOCATE C_CONTRATO_INSTITUICAO_MENSAL
END

EXEC SP_FATO_CONTRATO_INSTITUICAO_MENSAL '20230323'