USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_FATO_CONTRATO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @DATA_CONTRATO DATE,
			@COD_CONTRATO INT,
			@COD_MODALIDADE INT,
			@COD_INSTITUICAO INT,
			@NUMERO VARCHAR(8),
			@OBJETIVO_CONTRATO VARCHAR(99),
			@DATA_REALIZACAO DATE,
			@VALOR NUMERIC(10,2),
			@SITUACAO VARCHAR(45),
			@AVISO VARCHAR(45),
			@VENCEDORES VARCHAR(45),
			@ID_TEMPO BIGINT,
			@ID_INSTITUICAO INT,
			@ID_MODALIDADE INT,
			@ID_VIOLACAO INT


	DECLARE C_CONTRATO CURSOR FOR 			
	SELECT COD_MODALIDADE,COD_INSTITUICAO,COD_CONTRATO,DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES 
	FROM TB_AUX_CONTRATO
	WHERE @DATA_CARGA = DATA_CARGA

	OPEN C_CONTRATO
	FETCH C_CONTRATO INTO @COD_MODALIDADE,@COD_INSTITUICAO,@COD_CONTRATO,@DATA_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES


	WHILE @@FETCH_STATUS = 0
	BEGIN

		SET @ID_TEMPO = NULL
		SET @ID_INSTITUICAO = NULL
		SET @ID_MODALIDADE = NULL
		SET @ID_VIOLACAO = NULL

		SET @ID_TEMPO = (SELECT T.ID_TEMPO FROM DIM_TEMPO T WHERE T.DATA = @DATA_CONTRATO AND T.NIVEL='DIA')
		SET @ID_INSTITUICAO = (SELECT I.ID_INSTITUICAO FROM DIM_INSTITUICAO I WHERE I.COD_INSTITUICAO = @COD_INSTITUICAO)
		SET @ID_MODALIDADE = (SELECT M.ID_MODALIDADE FROM DIM_MODALIDADE M WHERE M.COD_MODALIDADE = @COD_MODALIDADE)

		IF @ID_TEMPO IS NULL OR @ID_INSTITUICAO IS NULL OR @ID_MODALIDADE IS NULL OR @VALOR <= 0 OR @DATA_REALIZACAO < @DATA_CONTRATO 
		BEGIN
				IF @ID_TEMPO IS NULL
				BEGIN
						INSERT INTO TB_VIO_CONTRATO (DATA_CARGA,DATA_CONTRATO,COD_MODALIDADE,COD_INSTITUICAO,COD_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,DT_ERRO, VIOLACAO)
						VALUES (@DATA_CARGA,@DATA_CONTRATO,@COD_MODALIDADE,@COD_INSTITUICAO,@COD_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES,GETDATE(),'DATA INVALIDA')
				END

				IF @ID_INSTITUICAO IS NULL
				BEGIN
						IF NOT EXISTS (SELECT 1 FROM TB_VIO_CONTRATO WHERE COD_CONTRATO = @COD_CONTRATO)
						BEGIN
								INSERT INTO TB_VIO_CONTRATO (DATA_CARGA,DATA_CONTRATO,COD_MODALIDADE,COD_INSTITUICAO,COD_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,DT_ERRO, VIOLACAO)
								VALUES (@DATA_CARGA,@DATA_CONTRATO,@COD_MODALIDADE,@COD_INSTITUICAO,@COD_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES,GETDATE(),'INSTITUIÇÃO INVALIDA')
						END
						ELSE
						BEGIN
								SELECT @ID_VIOLACAO = ID_VIOLACAO 
								FROM TB_VIO_CONTRATO 
								WHERE COD_CONTRATO = @COD_CONTRATO

								UPDATE TB_VIO_CONTRATO
								SET VIOLACAO = VIOLACAO + ', INSTITUIÇÃO INVALIDA'
								WHERE COD_CONTRATO = @COD_CONTRATO
						END
				END

				IF @ID_MODALIDADE IS NULL
				BEGIN
						IF NOT EXISTS (SELECT 1 FROM TB_VIO_CONTRATO WHERE COD_CONTRATO = @COD_CONTRATO)
						BEGIN
								INSERT INTO TB_VIO_CONTRATO (DATA_CARGA,DATA_CONTRATO,COD_MODALIDADE,COD_INSTITUICAO,COD_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,DT_ERRO, VIOLACAO)
								VALUES (@DATA_CARGA,@DATA_CONTRATO,@COD_MODALIDADE,@COD_INSTITUICAO,@COD_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES,GETDATE(),'MODALIDADE INVALIDA')
						END
						ELSE
						BEGIN
								SELECT @ID_VIOLACAO = ID_VIOLACAO 
								FROM TB_VIO_CONTRATO 
								WHERE COD_CONTRATO = @COD_CONTRATO

								UPDATE TB_VIO_CONTRATO
								SET VIOLACAO = VIOLACAO + ', MODALIDADE INVALIDA'
								WHERE COD_CONTRATO = @COD_CONTRATO
						END
				END

				IF  @VALOR <= 0
				BEGIN
						IF NOT EXISTS (SELECT 1 FROM TB_VIO_CONTRATO WHERE COD_CONTRATO = @COD_CONTRATO)
						BEGIN
								INSERT INTO TB_VIO_CONTRATO (DATA_CARGA,DATA_CONTRATO,COD_MODALIDADE,COD_INSTITUICAO,COD_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,DT_ERRO, VIOLACAO)
								VALUES (@DATA_CARGA,@DATA_CONTRATO,@COD_MODALIDADE,@COD_INSTITUICAO,@COD_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES,GETDATE(),'VALOR INVALIDO')
						END
						ELSE
						BEGIN
								SELECT @ID_VIOLACAO = ID_VIOLACAO 
								FROM TB_VIO_CONTRATO 
								WHERE COD_CONTRATO = @COD_CONTRATO

								UPDATE TB_VIO_CONTRATO
								SET VIOLACAO = VIOLACAO + ', VALOR INVALIDO'
								WHERE COD_CONTRATO = @COD_CONTRATO
						END
				END

				IF  @DATA_REALIZACAO < @DATA_CONTRATO
				BEGIN
						IF NOT EXISTS (SELECT 1 FROM TB_VIO_CONTRATO WHERE COD_CONTRATO = @COD_CONTRATO)
						BEGIN
								INSERT INTO TB_VIO_CONTRATO (DATA_CARGA,DATA_CONTRATO,COD_MODALIDADE,COD_INSTITUICAO,COD_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,DT_ERRO, VIOLACAO)
								VALUES (@DATA_CARGA,@DATA_CONTRATO,@COD_MODALIDADE,@COD_INSTITUICAO,@COD_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES,GETDATE(),'VALOR INVALIDO')
						END
						ELSE
						BEGIN
								SELECT @ID_VIOLACAO = ID_VIOLACAO 
								FROM TB_VIO_CONTRATO 
								WHERE COD_CONTRATO = @COD_CONTRATO

								UPDATE TB_VIO_CONTRATO
								SET VIOLACAO = VIOLACAO + ', DATA DA REALIZAÇÃO INVALIDA'
								WHERE COD_CONTRATO = @COD_CONTRATO
						END
				END
		END
		ELSE
		BEGIN
				IF NOT EXISTS (SELECT 1 FROM FATO_CONTRATO WHERE COD_CONTRATO = @COD_CONTRATO)
				BEGIN
					INSERT INTO FATO_CONTRATO(ID_TEMPO,ID_INSTITUICAO,ID_MODALIDADE,COD_CONTRATO,DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,QUANTIDADE)
					VALUES(@ID_TEMPO,@ID_INSTITUICAO,@ID_MODALIDADE,@COD_CONTRATO,@DATA_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES,1)		
				END
				ELSE
				BEGIN
					UPDATE FATO_CONTRATO
					SET ID_TEMPO = @ID_TEMPO,
						ID_INSTITUICAO = @ID_INSTITUICAO,
						ID_MODALIDADE = @ID_MODALIDADE,
						DATA_CONTRATO = @DATA_CONTRATO,
						NUMERO = @NUMERO,
						OBJETIVO_CONTRATO = @OBJETIVO_CONTRATO,
						DATA_REALIZACAO = @DATA_REALIZACAO,
						VALOR = @VALOR,
						SITUACAO = @SITUACAO,
						AVISO = @AVISO,
						VENCEDORES = @VENCEDORES
					WHERE COD_CONTRATO = @COD_CONTRATO		
				END
		END
		FETCH C_CONTRATO INTO @COD_MODALIDADE,@COD_INSTITUICAO,@COD_CONTRATO,@DATA_CONTRATO,@NUMERO,@OBJETIVO_CONTRATO,@DATA_REALIZACAO,@VALOR,@SITUACAO,@AVISO,@VENCEDORES

	END
	CLOSE C_CONTRATO
	DEALLOCATE C_CONTRATO
END



-- Teste

EXEC SP_FATO_CONTRATO'20240120'


SELECT * FROM FATO_CONTRATO
SELECT * FROM FATO_VEICULO
SELECT * FROM TB_VIO_CONTRATO

delete from TB_VIO_CONTRATO
delete from TB_AUX_CONTRATO


SELECT * FROM DIM_INSTITUICAO
SELECT * FROM DIM_MODALIDADE
SELECT * FROM DIM_SECRETARIA
SELECT * FROM DIM_TEMPO
SELECT * FROM DIM_TIPO_VEICULO

SELECT * FROM TB_AUX_MODALIDADE
SELECT * FROM TB_AUX_TIPO_VEICULO
SELECT * FROM TB_AUX_SECRETARIA
SELECT * FROM TB_AUX_INSTITUICAO
SELECT * FROM TB_AUX_VEICULO
SELECT * FROM TB_AUX_CONTRATO

-- Exemplo de inserts na tabela TB_AUX_CONTRATO
INSERT INTO TB_AUX_CONTRATO (DATA_CARGA, COD_MODALIDADE, COD_INSTITUICAO, COD_CONTRATO, DATA_CONTRATO, NUMERO, OBJETIVO_CONTRATO, DATA_REALIZACAO, VALOR, SITUACAO, AVISO, VENCEDORES)
VALUES 
('20230323', 1, 1001, 1, '20230330', '12345678', 'Fornecimento de materiais de escritório', '20230330', 5000.00, 'Concluído', 'Nenhum', 'Empresa A'),
('20230323', 2, 1002, 2, '20230330', '87654321', 'Serviços de limpeza', NULL, 3000.00, 'Pendente', 'Prorrogação', 'Empresa B'),
('20230323', 1, 1003, 3, '20230330', '98765432', 'Manutenção de equipamentos de informática', '20230330', 8000.00, 'Concluído', 'Nenhum', 'Empresa C');
