USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_OLTP_MODALIDADE (@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_MODALIDADE
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_MODALIDADE (DATA_CARGA, COD_MODALIDADE, TIPO)
			SELECT 
				@DATA_CARGA,
				M.COD_MODALIDADE,
				M.TIPO
			FROM 
				TB_MODALIDADE M

END

-- Teste

EXEC SP_OLTP_MODALIDADE '20240120'

SELECT * FROM TB_AUX_MODALIDADE
SELECT * FROM TB_MODALIDADE