USE PROJETO_LAGARTO

--ESTA COM ERROR

CREATE OR ALTER PROCEDURE SP_OLTP_GASTO (@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO TB_AUX_GASTO(DATA_CARGA,DATA_GASTO,COD_CONTRATO,COD_VEICULO,COD_INSTITUICAO,COD_SECRETARIA)			
		SELECT 
				@DATA_CARGA,
				C.DATA_CONTRATO AS DATA_GASTO,
				C.COD_CONTRATO,
				V.COD_VEICULO,
				I.COD_INSTITUICAO,
				S.COD_SECRETARIA
			FROM 
				TB_CONTRATO C
				INNER JOIN TB_INSTITUICAO I ON C.COD_INSTITUICAO = I.COD_INSTITUICAO
				INNER JOIN TB_VEICULO V ON C.COD_VEICULO = V.COD_VEICULO
				INNER JOIN TB_SECRETARIA S ON V.COD_SECRETARIA = S.COD_SECRETARIA
END






-- Teste

EXEC SP_OLTP_GASTO '20230323'