USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_OLTP_INSTITUICAO (@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO TB_AUX_INSTITUICAO (DATA_CARGA, COD_INSTITUICAO, NOME)
			SELECT 
				@DATA_CARGA,
				L.COD_INSTITUICAO,
				L.NOME
			FROM 
				TB_INSTITUICAO L

END



-- Teste

EXEC SP_OLTP_INSTITUICAO '20230323'

SELECT * FROM TB_AUX_INSTITUICAO