USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_OLTP_SECRETARIA (@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_SECRETARIA
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_SECRETARIA (DATA_CARGA, COD_SECRETARIA, NOME)
			SELECT 
				@DATA_CARGA,
				L.COD_SECRETARIA,
				L.NOME
			FROM 
				TB_SECRETARIA L
END




-- Teste

EXEC SP_OLTP_SECRETARIA '20240120'
SELECT * FROM TB_AUX_SECRETARIA

SELECT * FROM FATO_CONTRATO
SELECT * FROM FATO_VEICULO

SELECT * FROM DIM_INSTITUICAO
SELECT * FROM DIM_MODALIDADE
SELECT * FROM DIM_SECRETARIA
SELECT * FROM DIM_TEMPO
SELECT * FROM DIM_TIPO_VEICULO

SELECT * FROM TB_AUX_MODALIDADE
SELECT * FROM TB_AUX_TIPO_VEICULO
SELECT * FROM TB_AUX_SECRETARIA
SELECT * FROM TB_AUX_INSTITUICAO
SELECT * FROM TB_AUX_VEICULO
SELECT * FROM TB_AUX_CONTRATO

SELECT * FROM TB_VEICULO
SELECT * FROM TB_TIPO_VEICULO
SELECT * FROM TB_TIPO_OBSERVACAO
SELECT * FROM TB_SECRETARIA
SELECT * FROM TB_INSTITUICAO
