USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_OLTP_TIPO_VEICULO (@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO TB_AUX_TIPO_VEICULO (DATA_CARGA, COD_TIPO_VEICULO, NOME)
			SELECT 
				@DATA_CARGA,
				TV.COD_TIPO_VEICULO,
				TV.NOME
			FROM 
				TB_TIPO_VEICULO TV

END




-- Teste

EXEC SP_OLTP_TIPO_VEICULO '20230323'

SELECT * FROM TB_AUX_TIPO_VEICULO