USE PROJETO_LAGARTO

--ESTA COM ERROR

USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_OLTP_MODALIDADE (@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO TB_AUX_MODALIDADE (DATA_CARGA, COD_MODALIDADE, TIPO)
			SELECT 
				@DATA_CARGA,
				M.COD_MODALIDADE,
				M.TIPO
			FROM 
				TB_MODALIDADE M

END




-- Teste

EXEC SP_OLTP_MODALIDADE '20230323'

SELECT * FROM TB_AUX_MODALIDADE