USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_OLTP_SECRETARIA (@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO TB_AUX_SECRETARIA (DATA_CARGA, COD_SECRETARIA, NOME)
			SELECT 
				@DATA_CARGA,
				L.COD_SECRETARIA,
				L.NOME
			FROM 
				TB_SECRETARIA L

END




-- Teste

EXEC SP_OLTP_SECRETARIA '20230323'
SELECT * FROM TB_AUX_SECRETARIA
