-- Scripts ddl para o ambiente dimensional

USE PROJETO_LAGARTO

DROP TABLE FATO_COMPRA
DROP TABLE DIM_VEICULO
DROP TABLE DIM_CONTRATO
DROP TABLE DIM_TEMPO
DROP TABLE DIM_SECRETARIA
DROP TABLE DIM_INSTITUICAO


CREATE TABLE DIM_VEICULO (
   ID_VEICULO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   COD_VEICULO INT NOT NULL,
   PLACA VARCHAR(7) NOT NULL,
   MARCA VARCHAR(45) NOT NULL,
   MODELO VARCHAR(45) NOT NULL,
   ANO_FABRICACAO DATE NOT NULL,
   ANO_MODELO DATE NOT NULL,
   COR VARCHAR(45) NOT NULL,
   TIPO_VEICULO VARCHAR(45) NOT NULL,
   TIPO_OBSERVACAO VARCHAR(45)
)

CREATE TABLE DIM_CONTRATO (
	ID_CONTRATO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD_COTRATO INT NOT NULL,
	DATA_CONTRATO DATE NOT NULL,
	NUMERO VARCHAR(8) NOT NULL,
	OBJETIVO_CONTRATO VARCHAR(99) NOT NULL,
	DATA_REALIZACAO DATETIME,
	VALOR VARCHAR(45) NOT NULL,
	SITUACAO VARCHAR(45),
	AVISO VARCHAR(45),
	VENCEDORES VARCHAR(45),
	MODALIDADE VARCHAR(10),
)

CREATE TABLE DIM_SECRETARIA (
	ID_SECRETARIA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD_SECRETARIA INT NOT NULL,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE DIM_INSTITUICAO (
	ID_INSTITUICAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD_INSTITUICAO INT NOT NULL,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE DIM_TEMPO (
	ID_TEMPO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DATA DATETIME NOT NULL,
	DIA INT NOT NULL,
	DIA_SEMANA VARCHAR(50) NOT NULL,
	FIM_SEMANA VARCHAR(3) NOT NULL,
	MES INT NOT NULL,
	NOME_MES VARCHAR(100) NOT NULL,
	TRIMESTRE INT NOT NULL,
	NOME_TRIMESTRE VARCHAR(100) NOT NULL,
	SEMESTRE INT NOT NULL,
	NOME_SEMESTRE VARCHAR(100) NOT NULL,
	ANO INT NOT NULL
)

CREATE INDEX IX_DIM_TEMPO_DATA ON DIM_TEMPO (DATA)

CREATE TABLE FATO_GASTO (
	ID_GASTO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_VEICULO INT NOT NULL,
	ID_TEMPO BIGINT NOT NULL,
	ID_INSTITUICAO INT NOT NULL,
	ID_SECRETARIA INT NOT NULL,
	ID_CONTRATO INT NOT NULL,
	QUANTIDADE INT NOT NULL DEFAULT (1)
	CONSTRAINT FK_DIM_VEICULO FOREIGN KEY (ID_VEICULO) REFERENCES DIM_VEICULO (ID_VEICULO),
	CONSTRAINT FK_DIM_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES DIM_CONTRATO (ID_CONTRATO),
	CONSTRAINT FK_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
	CONSTRAINT FK_DIM_SECRETARIA FOREIGN KEY (ID_SECRETARIA) REFERENCES DIM_SECRETARIA (ID_SECRETARIA),
	CONSTRAINT FK_DIM_INSTITUICAO FOREIGN KEY (ID_INSTITUICAO) REFERENCES DIM_INSTITUICAO (ID_INSTITUICAO)
)


CREATE INDEX IX_FATO_GASTO_TEMPO ON FATO_GASTO(ID_TEMPO)
CREATE INDEX IX_FATO_GASTO_VEICULO ON FATO_GASTO(ID_VEICULO)
CREATE INDEX IX_FATO_GASTO_CONTRATO ON FATO_GASTO(ID_CONTRATO)
CREATE INDEX IX_FATO_GASTO_SECRETARIA ON FATO_GASTO(ID_SECRETARIA)
CREATE INDEX IX_FATO_GASTO_INSTITUICAO ON FATO_GASTO(ID_INSTITUICAO)



