USE PROJETO_LAGARTO

DROP TABLE TB_TIPO_VEICULO
DROP TABLE TB_INSTITUICAO
DROP TABLE TB_CONTRATO
DROP TABLE TB_TIPO_OBSERVACAO
DROP TABLE TB_MODALIDADE
DROP TABLE TB_SECRETARIA
DROP TABLE TB_VEICULO

CREATE TABLE TB_SECRETARIA (
	COD_SECRETARIA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_TIPO_VEICULO (
	COD_TIPO_VEICULO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_INSTITUICAO (
	COD_INSTITUICAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_TIPO_OBSERVACAO (
	COD_TIPO_OBSERVACAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TIPO_CAR VARCHAR(45)
)
 
 CREATE TABLE TB_MODALIDADE(
	COD_MODALIDADE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TIPO VARCHAR(10) NOT NULL
 )

CREATE TABLE TB_VEICULO (
	COD_VEICULO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PLACA VARCHAR(7) NOT NULL,
	MARCA VARCHAR(45) NOT NULL,
	MODELO VARCHAR(45) NOT NULL,
	ANO_FABRICACAO DATE NOT NULL,
	ANO_MODELO DATE NOT NULL,
	COR VARCHAR(45) NOT NULL,
	COD_TIPO_VEICULO INT NOT NULL CONSTRAINT FK_TIPO_VEICULO_TB_VEICULO FOREIGN KEY (COD_TIPO_VEICULO) REFERENCES TB_TIPO_VEICULO (COD_TIPO_VEICULO),
	COD_SECRETARIA INT NOT NULL CONSTRAINT FK_SECRETARIA_TB_VEICULO FOREIGN KEY (COD_SECRETARIA) REFERENCES TB_SECRETARIA (COD_SECRETARIA),
	COD_TIPO_OBSERVACAO INT NOT NULL CONSTRAINT FK_TIPO_OBSERVACAO_TB_VEICULO FOREIGN KEY (COD_TIPO_OBSERVACAO) REFERENCES TB_TIPO_OBSERVACAO (COD_TIPO_OBSERVACAO),
	COD_INSTITUICAO INT NOT NULL CONSTRAINT FK_INSTITUICAO_TB_VEICULO FOREIGN KEY (COD_INSTITUICAO) REFERENCES TB_INSTITUICAO (COD_INSTITUICAO)
) 

 CREATE TABLE TB_CONTRATO(
	COD_CONTRATO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DATA_CONTRATO DATE NOT NULL,
	NUMERO VARCHAR(8) NOT NULL,
	OBJETIVO_CONTRATO VARCHAR(99) NOT NULL,
	DATA_REALIZACAO DATETIME,
	VALOR VARCHAR(45) NOT NULL,
	SITUACAO VARCHAR(45),
	AVISO VARCHAR(45),
	VENCEDORES VARCHAR(45),
	COD_INSTITUICAO INT NOT NULL CONSTRAINT FK_INSTITUICAO_TB_CONTRATO FOREIGN KEY (COD_INSTITUICAO) REFERENCES TB_INSTITUICAO (COD_INSTITUICAO),
	COD_MODALIDADE INT NOT NULL CONSTRAINT FK_MODALIDADE_TB_CONTRATO FOREIGN KEY (COD_MODALIDADE) REFERENCES TB_MODALIDADE (COD_MODALIDADE)
 )

INSERT INTO TB_INSTITUICAO (nome) VALUES ('PML');
INSERT INTO TB_INSTITUICAO (nome) VALUES ( 'FMS');
INSERT INTO TB_INSTITUICAO (nome) VALUES ('FMAS');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEDURB');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMOP');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMED');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMAD');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMAGRI');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SMS');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEDEST');

INSERT INTO TB_TIPO_VEICULO (nome) VALUES ('Proprio');


INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('PIPA');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('DIESEL');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL  ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('ALCOOL/GASOLINA');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL  ONIBUS ESCOLAR ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL   NIBUS ESCOLAR ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL  ACESSIBILIDADE ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('CAMINHONETA DIESEL ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL ALCO/GASOL ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('VE CULO A DISPOSI  O DA APAE ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES (' LCOOL/GASOLINA');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('GASOLINA');


INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO1477', 'FIAT/PALIO','FIAT/PALIO', '01/01/2009', '01/01/2010', 'PRETA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OZE4944', 'M.BENZ/ATRON','M.BENZ/ATRON', '01/01/2013', '01/01/2013', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKS5752', 'FIAT STRADA WORKING','FIAT STRADA WORKING', '01/01/2015', '01/01/2015', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKO2067', 'M.BENZ/ATRON','M.BENZ/ATRON', '01/01/2013', '01/01/2013', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QME6314', 'VW/17.190 CRM 4X2','VW/17.190 CRM 4X2', '01/01/2018', '01/01/2018', 'BRANCA', 1, 1, 2, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKV6217', 'FORD/CARGO','FORD/CARGO', '01/01/2016', '01/01/2017', 'BRANCA', 1, 1, 3, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMF9223', 'VW/17.190 COLETOR','VW/17.190 COLETOR', '01/01/2019', '01/01/2019', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA1053', 'MMC/L200 TRITON','MMC/L200 TRITON', '01/01/2017', '01/01/2018', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMG7501', 'VW/17.190 CA AMBA','VW/17.190 CA AMBA', '01/01/2018', '01/01/2018', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAD2455', 'VW/24.250 CNC 6X2','VW/24.250 CNC 6X2', '01/01/2007', '01/01/2007', 'PRATA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD4047', 'VW AMAROK','VW AMAROK', '01/01/2018', '01/01/2018', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKY0739', 'RENAULT/OROCH','RENAULT/OROCH', '01/01/2016', '01/01/2017', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKW6757', 'YAMANHA/XTZ250 LANDER','YAMANHA/XTZ250 LANDER', '01/01/2016', '01/01/2016', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD4046', 'VW/AMAROK','VW/AMAROK', '01/01/2018', '01/01/2018', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'NVG4447', 'VW/GOL','VW/GOL', '01/01/2011', '01/01/2012', 'BRANCA', 1, 2, 5, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN0708', 'VW/MPOLO','VW/MPOLO', '01/01/2007', '01/01/2008', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OES5527', 'MARCOPOLO/VOLARE ','MARCOPOLO/VOLARE ', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP0153', 'MARCOPOLO/VOLARE  V8L','MARCOPOLO/VOLARE  V8L', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAM0708', 'VW/MPOLO IDEALE R','VW/MPOLO IDEALE R', '01/01/2007', '01/01/2008', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA8517', 'VW/NEOBUS/TRANSPORT','VW/NEOBUS/TRANSPORT', '01/01/2017', '01/01/2018', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMH3742', 'M.BENZ/CAIO LO916.ORE','M.BENZ/CAIO LO916.ORE', '01/01/2019', '01/01/2020', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA1875', 'MMC/L200 TRITON OUTDORA','MMC/L200 TRITON OUTDORA', '01/01/2017', '01/01/2018', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP0113', 'MARCOPOLO/VOLARE ','MARCOPOLO/VOLARE ', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP8706', 'VW/VOLARE IDEALE R','VW/VOLARE IDEALE R', '01/01/2007', '01/01/2008', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAL5632', 'MARCOPOLO/VOLARE VSL','MARCOPOLO/VOLARE VSL', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO3578', 'FIAT/PALIO','FIAT/PALIO', '01/01/2015', '01/01/2015', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMF7985', 'VW/ORE 1 ECOLAR','VW/ORE 1 ECOLAR', '01/01/2019', '01/01/2019', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO3678', 'FIAT/PALIO FIRE','FIAT/PALIO FIRE', '01/01/2015', '01/01/2015', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN9311', 'VW/INDUSCAR FOZ U','VW/INDUSCAR FOZ U', '01/01/2009', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN9351', 'VW/INDUSCAR FOZ U','VW/INDUSCAR FOZ U', '01/01/2009', '01/01/2009', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKR8646', 'FIAT/PALIO FIRE','FIAT/PALIO FIRE', '01/01/2015', '01/01/2015', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEM6806', 'VW/186CV','VW/186CV', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OES5537', 'MARCOPOLO/VOLARE','MARCOPOLO/VOLARE', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 3, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEM0890', 'VW/15.190','VW/15.190', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMF7981', 'VW/15.190','VW/15.190', '01/01/2019', '01/01/2019', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAH9235', 'MARCOPOLO/VOLARE V8L','MARCOPOLO/VOLARE V8L', '01/01/2009', '01/01/2009', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAL5762', 'MARCOPOLO/VOLARE V8 ESC','MARCOPOLO/VOLARE V8 ESC', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMH2223', 'ONIBUS RURAL ECOLAR ORE 1 4X4 DPM MPOLO /VOLARE','ONIBUS RURAL ECOLAR ORE 1 4X4 DPM MPOLO /VOLARE', '01/01/2019', '01/01/2019', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAH9255', 'MARCOPOLO/VOLARE V8L ESC','MARCOPOLO/VOLARE V8L ESC', '01/01/2009', '01/01/2009', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMI3904', 'CHEV/SPIN 18L MI PREMIER','CHEV/SPIN 18L MI PREMIER', '01/01/2019', '01/01/2020', 'BRANCA', 1, 4, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN9311', 'VWINDUSCAR FOZ U','VWINDUSCAR FOZ U', '01/01/2009', '01/01/2010', 'AMARELO', 1, 4, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMI3911', 'CHEV/ONIX JOY','CHEV/ONIX JOY', '01/01/2019', '01/01/2020', 'PRETA', 1, 4, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKS5233', 'FORD/CARGO','FORD/CARGO', '01/01/2015', '01/01/2015', 'BRANCA', 1, 5, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKS7314', 'FIAT/STRADA WORKING','FIAT/STRADA WORKING', '01/01/2015', '01/01/2015', 'BRANCA', 1, 5, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX5053', 'RENAULT CLIO','RENAULT CLIO', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKW8924', 'FIAT/DOBLO/ ATTRACTIV','FIAT/DOBLO/ ATTRACTIV', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMB1745', 'VW/NOVO GOL TL MBV','VW/NOVO GOL TL MBV', '01/01/2017', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKO0646', 'YAMAHA/XTZ 150 CROSSER E','YAMAHA/XTZ 150 CROSSER E', '01/01/2014', '01/01/2015', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMC6952', 'FIAT/MOBI LIKE','FIAT/MOBI LIKE', '01/01/2018', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD2052', 'FIAT DUCATO','FIAT DUCATO', '01/01/2018', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OER9332', 'FORD/FIESTA','FORD/FIESTA', '01/01/2014', '01/01/2014', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKO0584', 'YAMAHA/XTS 150','YAMAHA/XTS 150', '01/01/2014', '01/01/2015', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKN8238', 'VW/FOX CONNECT MB','VW/FOX CONNECT MB', '01/01/2018', '01/01/2019', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMB0387', 'L200/TRITON','L200/TRITON', '01/01/2017', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKW0336', 'L200/TRITON','L200/TRITON', '01/01/2015', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'NVL1956', 'FORD RANGER','FORD RANGER', '01/01/2011', '01/01/2011', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OMD3843', 'VW AMAROK ','VW AMAROK ', '01/01/2018', '01/01/2018', 'PRATA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX6422', 'FIAT/TORO FREEDOM','FIAT/TORO FREEDOM', '01/01/2016', '01/01/2017', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEK2107', 'FIAT/UNO MILLE ECONOMY','FIAT/UNO MILLE ECONOMY', '01/01/2012', '01/01/2013', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OES4381', 'FIAT/DOBLO ','FIAT/DOBLO ', '01/01/2014', '01/01/2014', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OER9331', 'FORD/FIESTA','FORD/FIESTA', '01/01/2014', '01/01/2014', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKN8238', 'VW/FOX CONNECT','VW/FOX CONNECT', '01/01/2018', '01/01/2019', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX5056', 'RENOULT CLIO','RENOULT CLIO', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX5054', 'RENAULT CLIO','RENAULT CLIO', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKN8558', 'VW/FOX CONNECT ','VW/FOX CONNECT ', '01/01/2018', '01/01/2019', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAK0122', 'VW/KOMBI','VW/KOMBI', '01/01/2010', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP8961', 'VW/KOMBI LOTA  O','VW/KOMBI LOTA  O', '01/01/2010', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO4632', 'SPRINTER','SPRINTER', '01/01/2009', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP9121', 'UNO MILLE','UNO MILLE', '01/01/2010', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKP3994', 'JINBEI SHINERAY PVAN','JINBEI SHINERAY PVAN', '01/01/2013', '01/01/2014', 'BRANCA', 1, 6, 13, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'HZX4627', 'AGRALE/6000','AGRALE/6000', '01/01/2005', '01/01/2006', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAF1818', 'VW/KOMBI LOTA  O','VW/KOMBI LOTA  O', '01/01/2007', '01/01/2008', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA1855', 'L200 TRITON','L200 TRITON', '01/01/2017', '01/01/2018', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKR8734', 'FIAT/DOBLO','FIAT/DOBLO', '01/01/2015', '01/01/2015', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAF9158', 'VW/KOMBI LOTA  O','VW/KOMBI LOTA  O', '01/01/2007', '01/01/2008', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEJ9105', 'FIAT/DODLO','FIAT/DODLO', '01/01/2012', '01/01/2012', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO1507', 'FIAT/UNO. MILE','FIAT/UNO. MILE', '01/01/2009', '01/01/2010', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKY4646', 'FIAT/DOBLO','FIAT/DOBLO', '01/01/2016', '01/01/2017', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKY5196', 'FIAT/DOBLO','FIAT/DOBLO', '01/01/2016', '01/01/2017', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKR7101', 'MARCOPOLO/VOLARE TCA','MARCOPOLO/VOLARE TCA', '01/01/2015', '01/01/2015', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAG9548', 'MAHINDRA ','MAHINDRA ', '01/01/2009', '01/01/2009', 'CINZA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD0955', 'CITROEN AIRCROSS 1.6 START','CITROEN AIRCROSS 1.6 START', '01/01/2018', '01/01/2019', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAE5760', 'TOYOTA HILUX 30 D','TOYOTA HILUX 30 D', '01/01/2006', '01/01/2007', 'PRATA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAA9259', 'FIAT UNO MILE FIRE','FIAT UNO MILE FIRE', '01/01/2006', '01/01/2006', 'BRANCA', 1, 1, 1, 1);



