USE Projeto_lagarto
DROP TABLE TB_SECRETARIA
DROP TABLE TB_VEICULO
DROP TABLE TB_TIPO_VEICULO
DROP TABLE TB_INSTITUICAO
DROP TABLE TB_CONTRATO
DROP TABLE TB_OBSERVACAO
DROP TABLE MODALIDADE

CREATE TABLE TB_SECRETARIA (
	COD_SECRETARIA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_TIPO_VEICULO (
	COD_TIPO_VEICULO INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE INSTITUICAO (
	COD_INSTITUICAO INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(45)
)

CREATE TABLE TIPO_OBSERVACAO (
	COD_TIPO_OBSERVACAO INT NOT NULL PRIMARY KEY,
	TIPO_CAR VARCHAR(45)
)

CREATE VEICULO (
	COD_VEICULO INT NOT NULL PRIMARY KEY,
	PLACA VARCHAR(7),
	ANO_FABRICACAO DATE NOT NULL,
	ANO_MODELO DATE NOT NULL,
	COR VARCHAR(45) NOT NULL,
	CONSTRAINT FK_TIPO FOREIGN KEY (COD_TIPO_VEICULO) REFERENCES TB_TIPO_VEICULO (COD_TIPO_VEICULO),
	CONSTRAINT FK_SECRETARIA FOREIGN KEY (COD_SECRETARIA) REFERENCES TB_SECRETARIA (COD_SECRETARIA)
) 