-- Scripts ddl para a área de staging

USE PROJETO_LAGARTO

DROP TABLE TB_AUX_VEICULO
DROP TABLE TB_AUX_CONTRATO
DROP TABLE TB_AUX_MODALIDADE
DROP TABLE TB_AUX_SECRETARIA
DROP TABLE TB_AUX_INSTITUICAO
DROP TABLE TB_AUX_TIPO_VEICULO

CREATE TABLE TB_AUX_SECRETARIA (
	DATA_CARGA DATETIME NOT NULL,
	COD_SECRETARIA INT NOT NULL,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_AUX_INSTITUICAO (
	DATA_CARGA DATETIME NOT NULL,
	COD_INSTITUICAO INT NOT NULL,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_AUX_TIPO_VEICULO (
	DATA_CARGA DATETIME NOT NULL,
	COD_TIPO_VEICULO INT NOT NULL,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_AUX_MODALIDADE (
	DATA_CARGA DATETIME NOT NULL,
	COD_MODALIDADE INT NOT NULL,
	TIPO VARCHAR(10) NOT NULL
)

CREATE TABLE TB_AUX_VEICULO (
   DATA_CARGA DATETIME NOT NULL,
   COD_TIPO_VEICULO INT NOT NULL,
   COD_SECRETARIA INT NOT NULL,
   COD_INSTITUICAO INT NOT NULL,
   COD_VEICULO INT NOT NULL,
   PLACA VARCHAR(7) NOT NULL,
   MARCA VARCHAR(45) NOT NULL,
   MODELO VARCHAR(45) NOT NULL,
   ANO_FABRICACAO DATE NOT NULL,
   ANO_MODELO DATE NOT NULL,
   COR VARCHAR(45) NOT NULL,
   TIPO_OBSERVACAO VARCHAR(45)
)

CREATE INDEX IX_AUX_VEICULO_DATA_CARGA ON TB_AUX_VEICULO(DATA_CARGA)

CREATE TABLE TB_AUX_CONTRATO (
	DATA_CARGA DATETIME NOT NULL,
	COD_MODALIDADE INT NOT NULL,
	COD_INSTITUICAO INT NOT NULL,
	COD_CONTRATO INT NOT NULL,
	DATA_CONTRATO DATE NOT NULL,
	NUMERO VARCHAR(8) NOT NULL,
	OBJETIVO_CONTRATO VARCHAR(99) NOT NULL,
	DATA_REALIZACAO DATETIME,
	VALOR VARCHAR(45) NOT NULL,
	SITUACAO VARCHAR(45),
	AVISO VARCHAR(45),
	VENCEDORES VARCHAR(45),
)

CREATE INDEX IX_AUX_CONTRATO_DATA_CARGA ON TB_AUX_CONTRATO(DATA_CARGA)