-- Scripts ddl para a área de staging

USE PROJETO_LAGARTO

DROP TABLE TB_AUX_VEICULO
DROP TABLE TB_AUX_CONTRATO
DROP TABLE TB_AUX_GASTO
DROP TABLE TB_AUX_SECRETARIA
DROP TABLE TB_AUX_INSTITUICAO

CREATE TABLE TB_AUX_VEICULO (
   DATA_CARGA DATETIME NOT NULL,
   COD_VEICULO INT NOT NULL,
   PLACA VARCHAR(7) NOT NULL,
   MARCA VARCHAR(45) NOT NULL,
   MODELO VARCHAR(45) NOT NULL,
   ANO_FABRICACAO DATE NOT NULL,
   ANO_MODELO DATE NOT NULL,
   COR VARCHAR(45) NOT NULL,
   TIPO_VEICULO VARCHAR(45) NOT NULL,
   TIPO_OBSERVACAO VARCHAR(45)
)

CREATE TABLE TB_AUX_CONTRATO (
	DATA_CARGA DATETIME NOT NULL,
	COD_COTRATO INT NOT NULL,
	DATA_CONTRATO DATE NOT NULL,
	NUMERO VARCHAR(8) NOT NULL,
	OBJETIVO_CONTRATO VARCHAR(99) NOT NULL,
	DATA_REALIZACAO DATETIME,
	VALOR VARCHAR(45) NOT NULL,
	SITUACAO VARCHAR(45),
	AVISO VARCHAR(45),
	VENCEDORES VARCHAR(45),
	MODALIDADE VARCHAR(10),
)

CREATE TABLE TB_AUX_SECRETARIA (
	DATA_CARGA DATETIME NOT NULL,
	COD_SECRETARIA INT NOT NULL,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_AUX_INSTITUICAO (
	DATA_CARGA DATETIME NOT NULL,
	COD_INSTITUICAO INT NOT NULL,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_AUX_GASTO (
	DATA_CARGA DATETIME NOT NULL,
	DATA_GASTO DATETIME NULL,
	COD_CONTRATO INT NULL,
	COD_VEICULO INT NULL,
	COD_INSTITUICAO INT NULL,
	COD_SECRETARIA INT NULL
)

CREATE INDEX IX_AUX_GASTO_DATA_CARGA ON TB_AUX_GASTO(DATA_CARGA)