USE PROJETO_LAGARTO

INSERT INTO TB_INSTITUICAO (nome) VALUES ('PML');
INSERT INTO TB_INSTITUICAO (nome) VALUES ( 'FMS');
INSERT INTO TB_INSTITUICAO (nome) VALUES ('FMAS');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEDURB');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMOP');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMED');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMAD');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEMAGRI');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SMS');
INSERT INTO TB_SECRETARIA (nome) VALUES ('SEDEST');

INSERT INTO TB_TIPO_VEICULO (nome) VALUES ('Proprio');


INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('PIPA');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('DIESEL');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL  ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('ALCOOL/GASOLINA');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL  ONIBUS ESCOLAR ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL   NIBUS ESCOLAR ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL DIESEL  ACESSIBILIDADE ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('CAMINHONETA DIESEL ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('COMBUST VEL ALCO/GASOL ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('VE CULO A DISPOSI  O DA APAE ');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES (' LCOOL/GASOLINA');
INSERT INTO TB_TIPO_OBSERVACAO (TIPO_CAR) VALUES ('GASOLINA');


INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO1477', 'FIAT/PALIO','FIAT/PALIO', '01/01/2009', '01/01/2010', 'PRETA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OZE4944', 'M.BENZ/ATRON','M.BENZ/ATRON', '01/01/2013', '01/01/2013', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKS5752', 'FIAT STRADA WORKING','FIAT STRADA WORKING', '01/01/2015', '01/01/2015', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKO2067', 'M.BENZ/ATRON','M.BENZ/ATRON', '01/01/2013', '01/01/2013', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QME6314', 'VW/17.190 CRM 4X2','VW/17.190 CRM 4X2', '01/01/2018', '01/01/2018', 'BRANCA', 1, 1, 2, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKV6217', 'FORD/CARGO','FORD/CARGO', '01/01/2016', '01/01/2017', 'BRANCA', 1, 1, 3, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMF9223', 'VW/17.190 COLETOR','VW/17.190 COLETOR', '01/01/2019', '01/01/2019', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA1053', 'MMC/L200 TRITON','MMC/L200 TRITON', '01/01/2017', '01/01/2018', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMG7501', 'VW/17.190 CA AMBA','VW/17.190 CA AMBA', '01/01/2018', '01/01/2018', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAD2455', 'VW/24.250 CNC 6X2','VW/24.250 CNC 6X2', '01/01/2007', '01/01/2007', 'PRATA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD4047', 'VW AMAROK','VW AMAROK', '01/01/2018', '01/01/2018', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKY0739', 'RENAULT/OROCH','RENAULT/OROCH', '01/01/2016', '01/01/2017', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKW6757', 'YAMANHA/XTZ250 LANDER','YAMANHA/XTZ250 LANDER', '01/01/2016', '01/01/2016', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD4046', 'VW/AMAROK','VW/AMAROK', '01/01/2018', '01/01/2018', 'BRANCA', 1, 2, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'NVG4447', 'VW/GOL','VW/GOL', '01/01/2011', '01/01/2012', 'BRANCA', 1, 2, 5, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN0708', 'VW/MPOLO','VW/MPOLO', '01/01/2007', '01/01/2008', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OES5527', 'MARCOPOLO/VOLARE ','MARCOPOLO/VOLARE ', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP0153', 'MARCOPOLO/VOLARE  V8L','MARCOPOLO/VOLARE  V8L', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAM0708', 'VW/MPOLO IDEALE R','VW/MPOLO IDEALE R', '01/01/2007', '01/01/2008', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA8517', 'VW/NEOBUS/TRANSPORT','VW/NEOBUS/TRANSPORT', '01/01/2017', '01/01/2018', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMH3742', 'M.BENZ/CAIO LO916.ORE','M.BENZ/CAIO LO916.ORE', '01/01/2019', '01/01/2020', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA1875', 'MMC/L200 TRITON OUTDORA','MMC/L200 TRITON OUTDORA', '01/01/2017', '01/01/2018', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP0113', 'MARCOPOLO/VOLARE ','MARCOPOLO/VOLARE ', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP8706', 'VW/VOLARE IDEALE R','VW/VOLARE IDEALE R', '01/01/2007', '01/01/2008', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAL5632', 'MARCOPOLO/VOLARE VSL','MARCOPOLO/VOLARE VSL', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO3578', 'FIAT/PALIO','FIAT/PALIO', '01/01/2015', '01/01/2015', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMF7985', 'VW/ORE 1 ECOLAR','VW/ORE 1 ECOLAR', '01/01/2019', '01/01/2019', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO3678', 'FIAT/PALIO FIRE','FIAT/PALIO FIRE', '01/01/2015', '01/01/2015', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN9311', 'VW/INDUSCAR FOZ U','VW/INDUSCAR FOZ U', '01/01/2009', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN9351', 'VW/INDUSCAR FOZ U','VW/INDUSCAR FOZ U', '01/01/2009', '01/01/2009', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKR8646', 'FIAT/PALIO FIRE','FIAT/PALIO FIRE', '01/01/2015', '01/01/2015', 'BRANCA', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEM6806', 'VW/186CV','VW/186CV', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OES5537', 'MARCOPOLO/VOLARE','MARCOPOLO/VOLARE', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 3, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEM0890', 'VW/15.190','VW/15.190', '01/01/2012', '01/01/2013', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMF7981', 'VW/15.190','VW/15.190', '01/01/2019', '01/01/2019', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAH9235', 'MARCOPOLO/VOLARE V8L','MARCOPOLO/VOLARE V8L', '01/01/2009', '01/01/2009', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAL5762', 'MARCOPOLO/VOLARE V8 ESC','MARCOPOLO/VOLARE V8 ESC', '01/01/2010', '01/01/2010', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMH2223', 'ONIBUS RURAL ECOLAR ORE 1 4X4 DPM MPOLO /VOLARE','ONIBUS RURAL ECOLAR ORE 1 4X4 DPM MPOLO /VOLARE', '01/01/2019', '01/01/2019', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAH9255', 'MARCOPOLO/VOLARE V8L ESC','MARCOPOLO/VOLARE V8L ESC', '01/01/2009', '01/01/2009', 'AMARELO', 1, 3, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMI3904', 'CHEV/SPIN 18L MI PREMIER','CHEV/SPIN 18L MI PREMIER', '01/01/2019', '01/01/2020', 'BRANCA', 1, 4, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAN9311', 'VWINDUSCAR FOZ U','VWINDUSCAR FOZ U', '01/01/2009', '01/01/2010', 'AMARELO', 1, 4, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMI3911', 'CHEV/ONIX JOY','CHEV/ONIX JOY', '01/01/2019', '01/01/2020', 'PRETA', 1, 4, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKS5233', 'FORD/CARGO','FORD/CARGO', '01/01/2015', '01/01/2015', 'BRANCA', 1, 5, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKS7314', 'FIAT/STRADA WORKING','FIAT/STRADA WORKING', '01/01/2015', '01/01/2015', 'BRANCA', 1, 5, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX5053', 'RENAULT CLIO','RENAULT CLIO', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKW8924', 'FIAT/DOBLO/ ATTRACTIV','FIAT/DOBLO/ ATTRACTIV', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMB1745', 'VW/NOVO GOL TL MBV','VW/NOVO GOL TL MBV', '01/01/2017', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKO0646', 'YAMAHA/XTZ 150 CROSSER E','YAMAHA/XTZ 150 CROSSER E', '01/01/2014', '01/01/2015', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMC6952', 'FIAT/MOBI LIKE','FIAT/MOBI LIKE', '01/01/2018', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD2052', 'FIAT DUCATO','FIAT DUCATO', '01/01/2018', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OER9332', 'FORD/FIESTA','FORD/FIESTA', '01/01/2014', '01/01/2014', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKO0584', 'YAMAHA/XTS 150','YAMAHA/XTS 150', '01/01/2014', '01/01/2015', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKN8238', 'VW/FOX CONNECT MB','VW/FOX CONNECT MB', '01/01/2018', '01/01/2019', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMB0387', 'L200/TRITON','L200/TRITON', '01/01/2017', '01/01/2018', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKW0336', 'L200/TRITON','L200/TRITON', '01/01/2015', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'NVL1956', 'FORD RANGER','FORD RANGER', '01/01/2011', '01/01/2011', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OMD3843', 'VW AMAROK ','VW AMAROK ', '01/01/2018', '01/01/2018', 'PRATA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX6422', 'FIAT/TORO FREEDOM','FIAT/TORO FREEDOM', '01/01/2016', '01/01/2017', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEK2107', 'FIAT/UNO MILLE ECONOMY','FIAT/UNO MILLE ECONOMY', '01/01/2012', '01/01/2013', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OES4381', 'FIAT/DOBLO ','FIAT/DOBLO ', '01/01/2014', '01/01/2014', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OER9331', 'FORD/FIESTA','FORD/FIESTA', '01/01/2014', '01/01/2014', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKN8238', 'VW/FOX CONNECT','VW/FOX CONNECT', '01/01/2018', '01/01/2019', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX5056', 'RENOULT CLIO','RENOULT CLIO', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKX5054', 'RENAULT CLIO','RENAULT CLIO', '01/01/2016', '01/01/2016', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKN8558', 'VW/FOX CONNECT ','VW/FOX CONNECT ', '01/01/2018', '01/01/2019', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAK0122', 'VW/KOMBI','VW/KOMBI', '01/01/2010', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP8961', 'VW/KOMBI LOTA  O','VW/KOMBI LOTA  O', '01/01/2010', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO4632', 'SPRINTER','SPRINTER', '01/01/2009', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAP9121', 'UNO MILLE','UNO MILLE', '01/01/2010', '01/01/2010', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKP3994', 'JINBEI SHINERAY PVAN','JINBEI SHINERAY PVAN', '01/01/2013', '01/01/2014', 'BRANCA', 1, 6, 13, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'HZX4627', 'AGRALE/6000','AGRALE/6000', '01/01/2005', '01/01/2006', 'BRANCA', 1, 6, 1, 2);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAF1818', 'VW/KOMBI LOTA  O','VW/KOMBI LOTA  O', '01/01/2007', '01/01/2008', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMA1855', 'L200 TRITON','L200 TRITON', '01/01/2017', '01/01/2018', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKR8734', 'FIAT/DOBLO','FIAT/DOBLO', '01/01/2015', '01/01/2015', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAF9158', 'VW/KOMBI LOTA  O','VW/KOMBI LOTA  O', '01/01/2007', '01/01/2008', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'OEJ9105', 'FIAT/DODLO','FIAT/DODLO', '01/01/2012', '01/01/2012', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAO1507', 'FIAT/UNO. MILE','FIAT/UNO. MILE', '01/01/2009', '01/01/2010', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKY4646', 'FIAT/DOBLO','FIAT/DOBLO', '01/01/2016', '01/01/2017', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKY5196', 'FIAT/DOBLO','FIAT/DOBLO', '01/01/2016', '01/01/2017', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QKR7101', 'MARCOPOLO/VOLARE TCA','MARCOPOLO/VOLARE TCA', '01/01/2015', '01/01/2015', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAG9548', 'MAHINDRA ','MAHINDRA ', '01/01/2009', '01/01/2009', 'CINZA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'QMD0955', 'CITROEN AIRCROSS 1.6 START','CITROEN AIRCROSS 1.6 START', '01/01/2018', '01/01/2019', 'BRANCA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAE5760', 'TOYOTA HILUX 30 D','TOYOTA HILUX 30 D', '01/01/2006', '01/01/2007', 'PRATA', 1, 1, 1, 1);
INSERT INTO TB_VEICULO (PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, COD_TIPO_VEICULO, COD_SECRETARIA, COD_TIPO_OBSERVACAO, COD_INSTITUICAO) 
 VALUES ( 'IAA9259', 'FIAT UNO MILE FIRE','FIAT UNO MILE FIRE', '01/01/2006', '01/01/2006', 'BRANCA', 1, 1, 1, 1);


INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Dispensa'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Pregão Presencial'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Registro de Preço'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Tomada de Preços'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Inexigibilidade'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Chamada Pública'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Concorrência'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Leilão'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Pregão Eletrônico'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Chamamento'); 
INSERT INTO TB_MODALIDADE (TIPO) VALUES ('Carta Convite'); 



 INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('24/02/2017','003/2017', 'Registro de Preços para futuro fornecimento de leites destinados ao atendimento das crianças que necessitam de leite especial para dieta ou suporte nutricional.','15/03/2017 14:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('23/02/2017','002/2017', 'Registro de Preços para futuro fornecimento parcelado de pneus, câmaras de ar e protetor de pneus ','15/03/2017 09:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('02/03/2017','003/2017', 'Contratação de empresa especializada para prestação de serviços para o desenvolvimento dos programas sociais nas unidades da Secretaria Municipal do Desenvolvimento Social e do Trabalho neste Município de Lagarto, Estado de Sergipe, conforme especificação do projeto básico e demais peças em anexo','14/03/2017 09:00', 100000, 'Suspenso' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('23/02/2017','001/2017', 'Contratação de empresa para o fornecimento de combustíveis automotivos -gasolina comum, óleo Diesel S10 e lubrificantes destinados aos veículos do Fundo Municipal de Saúde, durante o exercício de 2017, conforme especificações constante no Termo de Referência e no Anexo I.','13/03/2017 09:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('10/03/2017','015/2017', 'OBJETO: LOCAÇÃO DE UM IMÓVEL, SITUADO NA RUA I, Nº 109, CONJUNTO LAUDELINO FREIRE, NESTE MUNICÍPIO, PARA FUNCIONAMENTO COMO ANEXO DA SECRETARIA MUNICIPAL DA SEMDURB.','10/03/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('10/03/2017','014/2017', 'Locação de imóvel, situado na Rua José Cardoso de Andrade, 765, Pov. Jenipapo, para o funcionamento da Escola Municipal Infantil Vovó Aracay.','10/03/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('22/02/2017','002/2017', 'Fornecimento de combustíveis, (Gasolina Comum, Diesel S500 e Diesel S10 ) conforme especificações constantes do Anexo I, parte integrante deste Edital','09/03/2017 09:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('09/03/2017','013/2017', 'Contratação de empresa para locação de caminhão tipo prancha.','09/03/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('17/02/2017','001/2017', 'Contratação de empresa para fornecimento de Patrulha Mecanizada (Moto Niveladora) em atendimento ao Contrato de Repasse -CEF nº 2646.1033044-71/2016 , conforme especificação do termo de referencia em anexo.','06/03/2017 09:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('06/03/2017','017/2017', 'Contratação de empresa especializada em prestação de serviços de consertos de equipamentos odontológicos para atender os programas desenvolvidos pelo Fundo Municipal de Saúde.','06/03/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('06/03/2017','016/2017', 'Contratação de empresa para prestação de serviços de manutenção em uma unidade móvel  Odontológica, incluindo peças, visando viabilizar os atendimentos prestados aos pacientes SUS do Município de Lagar-to/SE, em caráter emergencial.','06/03/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('02/03/2017','015/2017', 'Locação de um imóvel, situado na Rua Josias Correia Fontes, 228, centro, neste município, para o funcionamento do Centro de Fisioterapia, conforme Laudo de Vistoria Técnica.','02/03/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('24/02/2017','014/2017', 'Contratação de empresa especializada na prestação de serviços de manutenção em aparelhos de ar condicionado para atender as necessidades das Unidades do Fundo Municipal de Saúde.','24/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('24/02/2017','013/2017', 'Aquisição de aparelhos de ar condicionado, compressor de ar condicionado e placa com controle remoto, destinados as Unidades vinculadas ao Fundo Municipal de Saúde, em caráter emergencial.','24/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('24/02/2017','005/2017', 'Locação de imóvel, situado na Rua José Vieira Filho, nº 528, Bairro: São José, neste município, para o funcionamento do CRAS.','24/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('23/02/2017','012/2017', 'Locação de um Imóvel, situado na Avenida Contorno BR, nº 830, Bairro Pratas, neste município, para o funcionamento da DTTU - Departamento de Trânsito e Transporte Urbano.','23/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('23/02/2017','004/2017', 'Locação de imóvel, situado na Rua Drº Laudelino Freire, nº 414, Bairro: São José, neste município, para o funcionamento da Secretaria de Desenvolvimento Social e do Trabalho.','23/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('23/02/2017','003/2017', 'Locação de imóvel, situado na Rua Major Mizael Vieira, nº 101, Centro, neste município, para o funcionamento do NAT - Núcleo de Apoio ao Trabalhador.','23/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('22/02/2017','011/2017', 'Locação de um imóvel, situado na Rua Jenolina Alves Souza, 584, São José, neste município, para funcionamento de uma CRECHE.','22/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('17/02/2017','012/2017', 'Contratação de empresa especializada em serviços de recarga de extintores, com o objetivo de atender o Fundo Municipal de Saúde e suas unidades de saúde vincula-das.','17/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('16/02/2017','011/2017', 'Contratação de empresa especializada em confecção de camisas e bolsas, para que sejam desenvolvidos os trabalhos e todas as atividades do Centro de Zoonoses, bem como a prestação dos serviços do CEREST/Lagarto, tendo em vista o evento do Dia Municipal de Trânsito, Saúde e Cidadania na cidade de Simão Dias e o dia Internacional da Mulher.','16/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('16/02/2017','010/2017', 'Locação de um imóvel, situado na Avenida Rotary, nº 137, centro, neste município, para o funcionamento da Secretaria Municipal de Esporte e Lazer.','16/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('16/02/2017','010/2017', 'Locação de um imóvel, situado na Av. Candido Barreto Machado, 435, bairro Laudelino Freire,  neste município, para o funcionamento do Centro de Referência de Saúde do Trabalhado (CEREST), conforme Laudo de Vistoria Técnica.','16/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('16/02/2017','006/2017', 'CONTRATAÇÃO D EMPRESA ESPECIALIZADA DE LOCAÇÃO DE SOFTWARE DE GESTÃO PÚBLICA (INSTALAÇÃO, TREINAMENTO, IMPLANTAÇÃO E SUPORTE TÉCNICO), COMPOSTO COM O SEGUINTE MÓDULO: PORTAL DO CONTRIBUINTE (NFS-e, ISS BANCO, CERTIDÃO ON-LINE).','16/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('07/02/2017','009/2017', 'Aquisição de gêneros alimentícios destinados aos programas e demais serviços vinculados ao Fundo Municipal de Saúde, em caráter emergencial.','07/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('07/02/2017','005/2017', 'O presente Contrato tem por objeto a contratação de serviços técnicos especializados de consultoria e assessoria técnico-legislativa, a serem prestados à Prefeitura Municipal Lagarto.','07/02/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('31/01/2017','009/2017', 'Locação de um imóvel, situado na Rua Major Mizael Vieira, 36, Centro, neste município, para o funcionamento da Secretaria Municipal de Obras.','31/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('23/01/2017','008/2017', 'Contratação de empresa visando à locação de Veículos tipo Popular e tipo Utilitário destinados aos serviços de deslocamento das equipes pertencentes aos programas deste Fundo Municipal de Saúde.','23/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('17/01/2017','006/2017', 'Contratação de empresa para o fornecimento de hortifrutigranjeiros destinados a merenda escolar visando atender dos alunos da rede pública municipal.','17/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('16/01/2017','007/2017', 'Contratação de empresa para aquisição emergencial de medicamentos não padronizados, listados na Revista ABC Farma.','16/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('13/01/2017','008/2017', 'Fornecimento de material de construção, elétrico e hidraulico, em caráter emergencial, para manutenção das secretarias, por este município.','13/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('13/01/2017','007/2017', 'Fornecimento de pneus, em caráter emergencial, para utilização dos veículos e máquinas utilizados por este município.','13/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('13/01/2017','006/2017', 'Contratação de empresa fornecimento parcelado de produtos médico-hospitalares destinados aos programas e demais serviços do Fundo Municipal de Saúde, em caráter emergencial.','13/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('13/01/2017','005/2017', 'Contratação de empresa para o fornecimento de gêneros alimentícios destinados a merenda escolar (perecíveis e não perecíveis), visando atender dos alunos da rede pública municipal.','13/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('13/01/2017','005/2017', 'Contratação de empresa para aquisição emergencial de medicamentos.','13/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('13/01/2017','004/2017', 'Aquisição de produtos de limpeza e higiene destinados aos programas e demais serviços vinculados ao Fundo Municipal de Saúde, em caráter emergencial.','13/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('12/01/2017','004/2017', 'Contratação de empresa para a locação de 20(vinte) máquinas copiadoras/multifuncionais , com serviço de manutenção, suporte técnico, periféricos e toner, visando atender as necessidades das secretarias municipais.','12/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('12/01/2017','003/2017', 'Contratação de empresa visando à locação de Veículos tipo Ônibus destinados ao Transporte de Servidores e pacientes em tratamentos em caráter emergencial.','12/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('12/01/2017','003/2017', 'Contratação de Empresa para Manutenção da Central de Regulação agendamento de consultas marcação e exames via internet, rede mundial de área, 24h por dia, 7 dias por semana, para ser utilizada em toda regional LAGARTO/SERGIPE ','12/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('12/01/2017','003/2017', 'CONTRATAÇÃO DE EMPRESA PARA O FORNECIMENTO DE ÁGUA MINERAL (20 LITROS) E BOTIJÃO DE GÁS LIQUEFEITO (GLP COM 13 KG), VISANDO ATENDER AS NECESSIDADES DAS SECRETARIAS MUNICIPAIS.','12/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('12/01/2017','002/2017', 'Fornecimento de maquinas copiadora/multifuncional, em caráter emergencial, para atendimento de atendimento dos programas sociais e demanda desta secretaria.','12/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('09/01/2017','004/2017', 'CONTRATAÇÃO DE EMPRESA ESPECIALIZADA PARA DISPONIBILIZAÇÃO DE ACESSO AO SISTEMA DE BANCO DE PREÇOS, CONFORME PROJETO BÁSICO.','09/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('06/01/2017','002/2017', 'Contratação de empresa para o fornecimento de almoço tipo quentinhas e refrigerantes de 2L, a fim de suprir as necessidades suprimento das Unidades de Atendimento de Saúde e do Fundo Municipal de Saúde, durante o exercício de 2017.','06/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('04/01/2017','002/2017', 'Prestação de serviços de Assessoria e Consultoria Técnica especializada na área de Contabilidade Pública e apoio administrativo, de acordo com as especificações constantes da Inexigibilidade de Licitação, seu Projeto Básico, e proposta do Contratado, que passam a fazer parte integrante deste instrumento, de acordo com o art. 55, XI da Lei nº. 8.666/93, independentemente de suas transcrições.','04/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('04/01/2017','002/2017', 'Contratação de empresa especializada para a prestação de serviços de sistema integrado de gestão Tributária, na condição de licença de uso.','04/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','003/2017', 'Contratação de empresa especializada de locação de Software de Gestão Pública (instalação, treinamento, implantação e suporte técnico), composto com os seguintes módulos: Planejamento Orçamentário (PPA, LOA, LDO), Administrativo e Financeiro','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','002/2017', 'Contratação de empresa especializada de locação de Software de Gestão Pública (instalação, treinamento, implantação e suporte técnico), composto com os seguintes módulos: Planejamento Orçamentário (PPA, LOA, LDO), Administrativo e Financeiro','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','002/2017', 'Contratação de empresa especializada na execução dos serviços d limpeza, conservação e manutenção de vias e logradouros públicos deste município, em caráter emergencial.','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','001/2017', 'Contratação de Empresa Especializada na prestação de serviços de locação de programas (incluindo instalação, treinamento, implantação e o suporte técnico), na versão Windows, envolvendo as áreas de acordo com a proposta apresentada pela Contratada.','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','001/2017', 'Fornecimento de combustiveis, em caráter emergencial, tais como gasolina comum e óleo diesel S10, para abastecimento dos veículos utilizados por esta Secretaria','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','001/2017', 'Prestação de serviços de Assessoria especializada na área de Contabilidade Pública e apoio administrativo, de acordo com as especificações constantes da Inexibilidade de Licitação, seu Projeto Básico, e proposta do Contratado, que passam a fazer parte integrante deste município.','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','001/2017', 'Fornecimento de combustíveis, tipo gasolina comum, óleo diesel e óleo lubrificante.','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','001/2017', 'O presente Contrato tem por objeto a prestação de serviços de Assessoria especializada na área de Contabilidade Pública e apoio administrativo, de acordo com as especificações constantes da Inexigibilidade de Licitação, seu Projeto Básico, e proposta do Contratado, que passam a fazer parte integrante deste instrumento, de acordo com o art. 55, XI da Lei nº. 8.666/93, independentemente de suas transcrições.','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
 VALUES ('03/01/2017','001/2017', 'Fornecimento de combustiveis, em caráter emergencial, tais como gasolina comum e óleos diesel S10 e S500, para abastecimento dos veículos e máquinas utilizados por este Município','03/01/2017 00:00', 100000, 'Concluído' ,'Sem aviso', 'Sem vencedor',1,1)
