USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_INSTITUICAO(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO DIM_INSTITUICAO (COD_INSTITUICAO, NOME)
			SELECT 
				I.COD_INSTITUICAO,
				I.NOME
			FROM 
				TB_AUX_INSTITUICAO I
END



-- Teste

EXEC SP_DIM_INSTITUICAO '20230323'

SELECT * FROM DIM_INSTITUICAO