USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_VEICULO(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO DIM_VEICULO (COD_VEICULO, PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, TIPO_VEICULO, TIPO_OBSERVACAO)
			SELECT 
				V.COD_VEICULO,
				V.PLACA,
				V.MARCA, 
				V.MODELO, 
				V.ANO_FABRICACAO, 
				V.ANO_MODELO, 
				V.COR, 
				V.TIPO_VEICULO, 
				V.TIPO_OBSERVACAO
			FROM 
				TB_AUX_VEICULO V
END



-- Teste

EXEC SP_DIM_VEICULO '20230323'