USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_CONTRATO(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO DIM_CONTRATO (COD_COTRATO,DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,MODALIDADE)
			SELECT 
				C.COD_COTRATO,
				C.DATA_CONTRATO,
				C.NUMERO,C.OBJETIVO_CONTRATO,
				C.DATA_REALIZACAO,
				C.VALOR,
				C.SITUACAO,
				C.AVISO,
				C.VENCEDORES,
				C.MODALIDADE
			FROM 
				TB_AUX_CONTRATO C
END



-- Teste

EXEC SP_DIM_CONTRATO '20230323'