USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_INSTITUICAO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_INSTITUICAO INT,
			@NOME VARCHAR(45),
			@CURRENT_INSTITUICAO VARCHAR(45)

	DECLARE CURSO CURSOR FOR 			
	SELECT COD_INSTITUICAO,NOME FROM TB_AUX_INSTITUICAO

	OPEN CURSO
	FETCH CURSO INTO @COD_INSTITUICAO, @NOME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS(SELECT 1 FROM DIM_INSTITUICAO WHERE COD_INSTITUICAO = @COD_INSTITUICAO))
		BEGIN
			SELECT @CURRENT_INSTITUICAO = NOME
			FROM DIM_INSTITUICAO
			WHERE COD_INSTITUICAO = @COD_INSTITUICAO

			IF(@CURRENT_INSTITUICAO!= @NOME)
				UPDATE DIM_INSTITUICAO
				SET NOME = @NOME
		END
		ELSE
		BEGIN
			INSERT INTO DIM_INSTITUICAO
			VALUES (@COD_INSTITUICAO,@NOME)
		END
		FETCH CURSO INTO @COD_INSTITUICAO, @NOME
	END
	CLOSE CURSO
	DEALLOCATE CURSO
END



-- Teste

EXEC SP_DIM_INSTITUICAO'20240120'
