USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_MODALIDADE(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO DIM_MODALIDADE (COD_MODALIDADE, TIPO)
			SELECT 
				M.COD_MODALIDADE,
				M.TIPO
			FROM 
				TB_AUX_MODALIDADE M
END



-- Teste

EXEC SP_DIM_MODALIDADE '20230323'

SELECT * FROM DIM_MODALIDADE