USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_SECRETARIA(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_SECRETARIA INT,
			@NOME VARCHAR(45),
			@CURRENT_SECRETARIA VARCHAR(45)

	DECLARE CURSO CURSOR FOR 			
	SELECT COD_SECRETARIA,NOME FROM TB_AUX_SECRETARIA

	OPEN CURSO
	FETCH CURSO INTO @COD_SECRETARIA, @NOME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS(SELECT 1 FROM DIM_SECRETARIA WHERE COD_SECRETARIA = @COD_SECRETARIA))
		BEGIN
			SELECT @CURRENT_SECRETARIA = NOME
			FROM DIM_SECRETARIA
			WHERE COD_SECRETARIA = @COD_SECRETARIA

			IF(@CURRENT_SECRETARIA != @NOME)
				UPDATE DIM_SECRETARIA
				SET NOME = @NOME
		END
		ELSE
		BEGIN
			INSERT INTO DIM_SECRETARIA
			VALUES (@COD_SECRETARIA,@NOME)
		END
		FETCH CURSO INTO @COD_SECRETARIA, @NOME
	END
	CLOSE CURSO
	DEALLOCATE CURSO
END



-- Teste

EXEC SP_DIM_SECRETARIA'20240120'

SELECT * FROM DIM_SECRETARIA