USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_SECRETARIA(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO DIM_SECRETARIA (COD_SECRETARIA, NOME)
			SELECT 
				S.COD_SECRETARIA,
				S.NOME
			FROM 
				TB_AUX_SECRETARIA S
END



-- Teste

EXEC SP_DIM_SECRETARIA '20230323'