USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_DIM_TIPO_VEICULO(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO DIM_TIPO_VEICULO (COD_TIPO_VEICULO, NOME)
			SELECT 
				TV.COD_TIPO_VEICULO,
				TV.NOME
			FROM 
				TB_AUX_TIPO_VEICULO TV
END



-- Teste

EXEC SP_DIM_TIPO_VEICULO '20230323'

SELECT * FROM DIM_TIPO_VEICULO