USE PROJETO_LAGARTO

DROP PROCEDURE SP_FATO_CONTRATO

CREATE OR ALTER PROCEDURE SP_FATO_CONTRATO(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO FATO_CONTRATO (ID_TEMPO,ID_INSTITUICAO,ID_MODALIDADE,COD_CONTRATO,DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES, QUANTIDADE)
			SELECT 
				T.ID_TEMPO,
				I.ID_INSTITUICAO,
				M.ID_MODALIDADE,
				C.COD_CONTRATO,
				C.DATA_CONTRATO,
				C.NUMERO,C.OBJETIVO_CONTRATO,
				C.DATA_REALIZACAO,
				C.VALOR,
				C.SITUACAO,
				C.AVISO,
				C.VENCEDORES,
				1
			FROM 
				TB_AUX_CONTRATO C
				INNER JOIN DIM_TEMPO T ON C.COD_CONTRATO = T.ID_TEMPO
				INNER JOIN DIM_INSTITUICAO I ON C.COD_CONTRATO = I.ID_INSTITUICAO
				INNER JOIN DIM_MODALIDADE M ON C.COD_CONTRATO = M.ID_MODALIDADE
END



-- Teste

EXEC SP_FATO_CONTRATO '20230323'

SELECT * FROM FATO_CONTRATO