USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_FATO_GASTO(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO FATO_GASTO(ID_CONTRATO,ID_VEICULO,ID_TEMPO,ID_INSTITUICAO,ID_SECRETARIA,COD_GASTO,QUANTIDADE)
			SELECT 
				C.ID_CONTRATO,
				V.ID_VEICULO,
				T.ID_TEMPO,
				I.ID_INSTITUICAO,
				S.ID_SECRETARIA,
				G.COD_GASTO,
				1
			FROM 
				TB_AUX_GASTO G
				INNER JOIN DIM_TEMPO T ON G.COD_GASTO = T.ID_TEMPO
				INNER JOIN DIM_VEICULO V ON G.COD_GASTO = V.ID_VEICULO
				INNER JOIN DIM_CONTRATO C ON G.COD_GASTO = C.ID_CONTRATO
				INNER JOIN DIM_SECRETARIA S ON G.COD_GASTO = S.ID_SECRETARIA
				INNER JOIN DIM_INSTITUICAO I ON G.COD_GASTO = I.ID_INSTITUICAO
END



-- Teste

EXEC SP_FATO_GASTO '20230323'