USE PROJETO_LAGARTO

CREATE OR ALTER PROCEDURE SP_FATO_VEICULO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_TIPO_VEICULO INT,
			@COD_SECRETARIA INT,
			@COD_INSTITUICAO INT, 
			@COD_VEICULO BIGINT,
			@PLACA VARCHAR(7),
			@MARCA VARCHAR(45),
			@MODELO VARCHAR(45),
			@ANO_FABRICACAO DATE,
			@ANO_MODELO DATE,
			@COR VARCHAR(45),
			@TIPO_OBSERVACAO VARCHAR(45),
			@ID_TIPO_VEICULO INT,
			@ID_TEMPO BIGINT,
			@ID_INSTITUICAO INT,
			@ID_SECRETARIA INT

	DECLARE CURSO CURSOR FOR 			
	SELECT COD_TIPO_VEICULO,COD_SECRETARIA,COD_INSTITUICAO,COD_VEICULO,PLACA,MARCA,MODELO,ANO_FABRICACAO,ANO_MODELO,COR,TIPO_OBSERVACAO
	FROM TB_AUX_VEICULO
	WHERE @DATA_CARGA = DATA_CARGA

	OPEN CURSO
	FETCH CURSO INTO @COD_TIPO_VEICULO,@COD_SECRETARIA,@COD_INSTITUICAO,@COD_VEICULO,@PLACA,@MARCA,@MODELO,@ANO_FABRICACAO,@ANO_MODELO,@COR,@TIPO_OBSERVACAO

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT @ID_TEMPO = ID_TEMPO
		FROM DIM_TEMPO
		WHERE DATA = @ANO_FABRICACAO

		SELECT @ID_INSTITUICAO = ID_INSTITUICAO
		FROM DIM_INSTITUICAO
		WHERE COD_INSTITUICAO = @COD_INSTITUICAO

		SELECT @ID_SECRETARIA = ID_SECRETARIA
		FROM DIM_SECRETARIA
		WHERE COD_SECRETARIA = @COD_SECRETARIA

		SELECT @ID_TIPO_VEICULO = ID_TIPO_VEICULO
		FROM DIM_TIPO_VEICULO
		WHERE COD_TIPO_VEICULO = @COD_TIPO_VEICULO

		IF(EXISTS(SELECT 1 FROM FATO_VEICULO WHERE COD_VEICULO = @COD_VEICULO))
		BEGIN
			UPDATE FATO_VEICULO
			SET ID_TIPO_VEICULO = @ID_TIPO_VEICULO,
				ID_SECRETARIA = @ID_SECRETARIA,
				ID_INSTITUICAO = @ID_INSTITUICAO,
				ID_TEMPO = @ID_TEMPO,
				PLACA = @PLACA,
				MARCA = @MARCA,
				MODELO = @MODELO,
				ANO_FABRICACAO = @ANO_FABRICACAO,
				ANO_MODELO = @ANO_MODELO,
				COR = @COR,
				TIPO_OBSERVACAO =@TIPO_OBSERVACAO
			WHERE COD_VEICULO = @COD_VEICULO
		END
		ELSE
		BEGIN
			INSERT INTO FATO_VEICULO(ID_TEMPO,ID_TIPO_VEICULO,ID_SECRETARIA,ID_INSTITUICAO,COD_VEICULO, PLACA, MARCA, MODELO, ANO_FABRICACAO, ANO_MODELO, COR, TIPO_OBSERVACAO,QUANTIDADE)
			VALUES(@ID_TEMPO,@ID_TIPO_VEICULO,@ID_SECRETARIA,@ID_INSTITUICAO,@COD_VEICULO, @PLACA, @MARCA, @MODELO, @ANO_FABRICACAO, @ANO_MODELO, @COR, @TIPO_OBSERVACAO,1)
		END

		FETCH CURSO INTO @COD_TIPO_VEICULO,@COD_SECRETARIA,@COD_INSTITUICAO,@COD_VEICULO,@PLACA,@MARCA,@MODELO,@ANO_FABRICACAO,@ANO_MODELO,@COR,@TIPO_OBSERVACAO

	END
	CLOSE CURSO
	DEALLOCATE CURSO
END



-- Teste

EXEC SP_FATO_VEICULO'20230323'


SELECT * FROM FATO_CONTRATO
SELECT * FROM FATO_VEICULO

SELECT * FROM DIM_INSTITUICAO
SELECT * FROM DIM_MODALIDADE
SELECT * FROM DIM_SECRETARIA
SELECT * FROM DIM_TEMPO
SELECT * FROM DIM_TIPO_VEICULO

SELECT * FROM TB_AUX_MODALIDADE
SELECT * FROM TB_AUX_TIPO_VEICULO
SELECT * FROM TB_AUX_SECRETARIA
SELECT * FROM TB_AUX_INSTITUICAO
SELECT * FROM TB_AUX_VEICULO
SELECT * FROM TB_AUX_CONTRATO