USE PROJETO_LAGARTO

DROP TABLE TB_TIPO_VEICULO
DROP TABLE TB_INSTITUICAO
DROP TABLE TB_CONTRATO
DROP TABLE TB_TIPO_OBSERVACAO
DROP TABLE TB_MODALIDADE
DROP TABLE TB_SECRETARIA
DROP TABLE TB_VEICULO

CREATE TABLE TB_SECRETARIA (
	COD_SECRETARIA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_TIPO_VEICULO (
	COD_TIPO_VEICULO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_INSTITUICAO (
	COD_INSTITUICAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

CREATE TABLE TB_TIPO_OBSERVACAO (
	COD_TIPO_OBSERVACAO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TIPO_CAR VARCHAR(45)
)
 
 CREATE TABLE TB_MODALIDADE(
	COD_MODALIDADE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TIPO VARCHAR(999) NOT NULL
 )

CREATE TABLE TB_VEICULO (
	COD_VEICULO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PLACA VARCHAR(7) NOT NULL,
	MARCA VARCHAR(45) NOT NULL,
	MODELO VARCHAR(45) NOT NULL,
	ANO_FABRICACAO DATE NOT NULL,
	ANO_MODELO DATE NOT NULL,
	COR VARCHAR(45) NOT NULL,
	COD_TIPO_VEICULO INT NOT NULL CONSTRAINT FK_TIPO_VEICULO_TB_VEICULO FOREIGN KEY (COD_TIPO_VEICULO) REFERENCES TB_TIPO_VEICULO (COD_TIPO_VEICULO),
	COD_SECRETARIA INT NOT NULL CONSTRAINT FK_SECRETARIA_TB_VEICULO FOREIGN KEY (COD_SECRETARIA) REFERENCES TB_SECRETARIA (COD_SECRETARIA),
	COD_TIPO_OBSERVACAO INT NOT NULL CONSTRAINT FK_TIPO_OBSERVACAO_TB_VEICULO FOREIGN KEY (COD_TIPO_OBSERVACAO) REFERENCES TB_TIPO_OBSERVACAO (COD_TIPO_OBSERVACAO),
	COD_INSTITUICAO INT NOT NULL CONSTRAINT FK_INSTITUICAO_TB_VEICULO FOREIGN KEY (COD_INSTITUICAO) REFERENCES TB_INSTITUICAO (COD_INSTITUICAO)
) 

 CREATE TABLE TB_CONTRATO(
	COD_CONTRATO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DATA_CONTRATO DATE NOT NULL,
	NUMERO VARCHAR(8) NOT NULL,
	OBJETIVO_CONTRATO VARCHAR(999) NOT NULL,
	DATA_REALIZACAO DATE,
	VALOR NUMERIC(10,2) NOT NULL,
	SITUACAO VARCHAR(45),
	AVISO VARCHAR(45),
	VENCEDORES VARCHAR(45),
	COD_INSTITUICAO INT NOT NULL CONSTRAINT FK_INSTITUICAO_TB_CONTRATO FOREIGN KEY (COD_INSTITUICAO) REFERENCES TB_INSTITUICAO (COD_INSTITUICAO),
	COD_MODALIDADE INT NOT NULL CONSTRAINT FK_MODALIDADE_TB_CONTRATO FOREIGN KEY (COD_MODALIDADE) REFERENCES TB_MODALIDADE (COD_MODALIDADE)
 )

 select * from TB_CONTRATO
 select * from TB_SECRETARIA
 select * from TB_MODALIDADE
 insert into TB_MODALIDADE(TIPO) values ('Tomada de Preços')

 insert into TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) values ('18/12/2013','056/2013','testes','01/01/2023 09:00',5000,'teste de situacao ','teste de avisos', 'teste vencedor',1,1)

INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
VALUES ('12/12/2023','001/2017', 'teste','03/01/2017', 55000, 'Concluído','teste de aviso', 'teste de vencedor',1,1)


INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
VALUES ('18/12/2013','056/2013', 'Contratação de empresa para confecções de painéis, placas e lonas de impressão DGI, bem como, reforma de painel em impressão DGI.','nan', Concluído, '18/12/2013', 'teste de aviso', 'teste de vencedor',1,1)


INSERT INTO TB_CONTRATO (DATA_CONTRATO,NUMERO,OBJETIVO_CONTRATO,DATA_REALIZACAO,VALOR,SITUACAO,AVISO,VENCEDORES,COD_INSTITUICAO,COD_MODALIDADE) 
VALUES ('18/12/2013','056/2013', 'Contratação de empresa para confecções de painéis, placas e lonas de impressão DGI, bem como, reforma de painel em impressão DGI.',5000, 'Concluído', '18/12/2013', 'teste de aviso', 'teste de vencedor',1,1)
