-- Script para povoar a dimensão tempo
USE PROJETO_LAGARTO
	
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO (@DT_INICIAL DATETIME, @DT_FINAL DATETIME)
AS
BEGIN
	WHILE (@DT_INICIAL <= @DT_FINAL)
	BEGIN
		DECLARE @ANO_ATUAL INT = YEAR(@DT_INICIAL)

		INSERT INTO DIM_TEMPO (NIVEL, ANO)
		VALUES ('ANO', @ANO_ATUAL)
			

		WHILE (@ANO_ATUAL = YEAR(@DT_INICIAL) AND @DT_INICIAL <= @DT_FINAL)
		BEGIN
			DECLARE @NOME_TRI VARCHAR(20),
					@NOME_SEM VARCHAR(20),
					@NUM_SEM INT,
					@MES_ATUAL INT = MONTH(@DT_INICIAL)

			IF(DATEPART(QQ, @DT_INICIAL) = 1)
			BEGIN
				SET @NOME_TRI = '1º Trimestre'
				SET @NOME_SEM = '1º Semestre'
				SET @NUM_SEM = 1
			END
			IF(DATEPART(QQ, @DT_INICIAL) = 2)
			BEGIN
				SET @NOME_TRI = '2º Trimestre'
				SET @NOME_SEM = '1º Semestre'
				SET @NUM_SEM = 1
			END
			IF(DATEPART(QQ, @DT_INICIAL) = 3)
			BEGIN
				SET @NOME_TRI = '3º Trimestre'
				SET @NOME_SEM = '2º Semestre'
				SET @NUM_SEM = 2
			END
			IF(DATEPART(QQ, @DT_INICIAL) = 4)
			BEGIN
				SET @NOME_TRI = '4º Trimestre'
				SET @NOME_SEM = '2º Semestre'
				SET @NUM_SEM = 2
			END

			INSERT INTO DIM_TEMPO (NIVEL, MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE,SEMESTRE, NOME_SEMESTRE, ANO)
			VALUES ('MES', MONTH(@DT_INICIAL), DATENAME(MM,@DT_INICIAL), DATEPART(QQ, @DT_INICIAL), @NOME_TRI, @NUM_SEM, @NOME_SEM, YEAR(@DT_INICIAL))

			WHILE (@MES_ATUAL = MONTH(@DT_INICIAL) AND @ANO_ATUAL = YEAR(@DT_INICIAL))
			BEGIN
				DECLARE @FIM_SEM VARCHAR(3) = 'NAO'
					
				IF(DATENAME(WEEKDAY, @DT_INICIAL) = 'Domingo' OR DATENAME(WEEKDAY, @DT_INICIAL) = 'S�bado')
					SET @FIM_SEM = 'SIM'

				INSERT INTO DIM_TEMPO VALUES
				('DIA', @DT_INICIAL, DAY(@DT_INICIAL), DATENAME(WEEKDAY, @DT_INICIAL), @FIM_SEM, NULL, 'NAO', DATEPART(MM, @DT_INICIAL), DATENAME(MM, @DT_INICIAL), DATEPART(QQ, @DT_INICIAL), @NOME_TRI, @NUM_SEM, @NOME_SEM, YEAR(@DT_INICIAL))

				SET @DT_INICIAL = DATEADD(DAY, 1, @DT_INICIAL)
			END
		END
	END
END

EXEC SP_DIM_TEMPO '20090101', '20200101'

TRUNCATE TABLE DIM_TEMPO

SELECT * FROM DIM_TEMPO
ORDER BY ANO